// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_pb_common.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "data_pb_common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protos {

namespace {

const ::google::protobuf::Descriptor* pb_table_field_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  pb_table_field_reflection_ = NULL;
const ::google::protobuf::Descriptor* pb_table_item_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  pb_table_item_reflection_ = NULL;
const ::google::protobuf::Descriptor* pb_data_module_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  pb_data_module_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_data_5fpb_5fcommon_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_data_5fpb_5fcommon_2eproto() {
  protobuf_AddDesc_data_5fpb_5fcommon_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "data_pb_common.proto");
  GOOGLE_CHECK(file != NULL);
  pb_table_field_descriptor_ = file->message_type(0);
  static const int pb_table_field_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_field, val_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_field, field_index_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_field, val_f_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_field, val_int_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_field, val_bigint_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_field, val_str_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_field, val_bool_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_field, primary_),
  };
  pb_table_field_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      pb_table_field_descriptor_,
      pb_table_field::default_instance_,
      pb_table_field_offsets_,
      -1,
      -1,
      -1,
      sizeof(pb_table_field),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_field, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_field, _is_default_instance_));
  pb_table_item_descriptor_ = file->message_type(1);
  static const int pb_table_item_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_item, field_list_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_item, db_status_),
  };
  pb_table_item_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      pb_table_item_descriptor_,
      pb_table_item::default_instance_,
      pb_table_item_offsets_,
      -1,
      -1,
      -1,
      sizeof(pb_table_item),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_item, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_table_item, _is_default_instance_));
  pb_data_module_descriptor_ = file->message_type(2);
  static const int pb_data_module_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_data_module, table_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_data_module, data_items_),
  };
  pb_data_module_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      pb_data_module_descriptor_,
      pb_data_module::default_instance_,
      pb_data_module_offsets_,
      -1,
      -1,
      -1,
      sizeof(pb_data_module),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_data_module, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(pb_data_module, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_data_5fpb_5fcommon_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      pb_table_field_descriptor_, &pb_table_field::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      pb_table_item_descriptor_, &pb_table_item::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      pb_data_module_descriptor_, &pb_data_module::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_data_5fpb_5fcommon_2eproto() {
  delete pb_table_field::default_instance_;
  delete pb_table_field_reflection_;
  delete pb_table_item::default_instance_;
  delete pb_table_item_reflection_;
  delete pb_data_module::default_instance_;
  delete pb_data_module_reflection_;
}

void protobuf_AddDesc_data_5fpb_5fcommon_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_data_5fpb_5fcommon_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024data_pb_common.proto\022\006protos\"\237\001\n\016pb_ta"
    "ble_field\022\020\n\010val_type\030\001 \001(\005\022\023\n\013field_ind"
    "ex\030\002 \001(\005\022\r\n\005val_f\030\003 \001(\002\022\017\n\007val_int\030\004 \001(\005"
    "\022\022\n\nval_bigint\030\005 \001(\003\022\017\n\007val_str\030\006 \001(\t\022\020\n"
    "\010val_bool\030\007 \001(\010\022\017\n\007primary\030\010 \001(\010\"N\n\rpb_t"
    "able_item\022*\n\nfield_list\030\001 \003(\0132\026.protos.p"
    "b_table_field\022\021\n\tdb_status\030\002 \001(\005\"M\n\016pb_d"
    "ata_module\022\020\n\010table_id\030\001 \001(\005\022)\n\ndata_ite"
    "ms\030\002 \003(\0132\025.protos.pb_table_itemb\006proto3", 359);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "data_pb_common.proto", &protobuf_RegisterTypes);
  pb_table_field::default_instance_ = new pb_table_field();
  pb_table_item::default_instance_ = new pb_table_item();
  pb_data_module::default_instance_ = new pb_data_module();
  pb_table_field::default_instance_->InitAsDefaultInstance();
  pb_table_item::default_instance_->InitAsDefaultInstance();
  pb_data_module::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_data_5fpb_5fcommon_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_data_5fpb_5fcommon_2eproto {
  StaticDescriptorInitializer_data_5fpb_5fcommon_2eproto() {
    protobuf_AddDesc_data_5fpb_5fcommon_2eproto();
  }
} static_descriptor_initializer_data_5fpb_5fcommon_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int pb_table_field::kValTypeFieldNumber;
const int pb_table_field::kFieldIndexFieldNumber;
const int pb_table_field::kValFFieldNumber;
const int pb_table_field::kValIntFieldNumber;
const int pb_table_field::kValBigintFieldNumber;
const int pb_table_field::kValStrFieldNumber;
const int pb_table_field::kValBoolFieldNumber;
const int pb_table_field::kPrimaryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

pb_table_field::pb_table_field()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protos.pb_table_field)
}

void pb_table_field::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

pb_table_field::pb_table_field(const pb_table_field& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protos.pb_table_field)
}

void pb_table_field::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  val_type_ = 0;
  field_index_ = 0;
  val_f_ = 0;
  val_int_ = 0;
  val_bigint_ = GOOGLE_LONGLONG(0);
  val_str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  val_bool_ = false;
  primary_ = false;
}

pb_table_field::~pb_table_field() {
  // @@protoc_insertion_point(destructor:protos.pb_table_field)
  SharedDtor();
}

void pb_table_field::SharedDtor() {
  val_str_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void pb_table_field::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* pb_table_field::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return pb_table_field_descriptor_;
}

const pb_table_field& pb_table_field::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_data_5fpb_5fcommon_2eproto();
  return *default_instance_;
}

pb_table_field* pb_table_field::default_instance_ = NULL;

pb_table_field* pb_table_field::New(::google::protobuf::Arena* arena) const {
  pb_table_field* n = new pb_table_field;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void pb_table_field::Clear() {
// @@protoc_insertion_point(message_clear_start:protos.pb_table_field)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(pb_table_field, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<pb_table_field*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(val_type_, val_bigint_);
  ZR_(val_bool_, primary_);
  val_str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool pb_table_field::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protos.pb_table_field)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 val_type = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &val_type_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_field_index;
        break;
      }

      // optional int32 field_index = 2;
      case 2: {
        if (tag == 16) {
         parse_field_index:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &field_index_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_val_f;
        break;
      }

      // optional float val_f = 3;
      case 3: {
        if (tag == 29) {
         parse_val_f:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &val_f_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_val_int;
        break;
      }

      // optional int32 val_int = 4;
      case 4: {
        if (tag == 32) {
         parse_val_int:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &val_int_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_val_bigint;
        break;
      }

      // optional int64 val_bigint = 5;
      case 5: {
        if (tag == 40) {
         parse_val_bigint:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &val_bigint_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_val_str;
        break;
      }

      // optional string val_str = 6;
      case 6: {
        if (tag == 50) {
         parse_val_str:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_val_str()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->val_str().data(), this->val_str().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protos.pb_table_field.val_str"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_val_bool;
        break;
      }

      // optional bool val_bool = 7;
      case 7: {
        if (tag == 56) {
         parse_val_bool:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &val_bool_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_primary;
        break;
      }

      // optional bool primary = 8;
      case 8: {
        if (tag == 64) {
         parse_primary:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &primary_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protos.pb_table_field)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protos.pb_table_field)
  return false;
#undef DO_
}

void pb_table_field::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protos.pb_table_field)
  // optional int32 val_type = 1;
  if (this->val_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->val_type(), output);
  }

  // optional int32 field_index = 2;
  if (this->field_index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->field_index(), output);
  }

  // optional float val_f = 3;
  if (this->val_f() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->val_f(), output);
  }

  // optional int32 val_int = 4;
  if (this->val_int() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->val_int(), output);
  }

  // optional int64 val_bigint = 5;
  if (this->val_bigint() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->val_bigint(), output);
  }

  // optional string val_str = 6;
  if (this->val_str().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->val_str().data(), this->val_str().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protos.pb_table_field.val_str");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->val_str(), output);
  }

  // optional bool val_bool = 7;
  if (this->val_bool() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->val_bool(), output);
  }

  // optional bool primary = 8;
  if (this->primary() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->primary(), output);
  }

  // @@protoc_insertion_point(serialize_end:protos.pb_table_field)
}

::google::protobuf::uint8* pb_table_field::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protos.pb_table_field)
  // optional int32 val_type = 1;
  if (this->val_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->val_type(), target);
  }

  // optional int32 field_index = 2;
  if (this->field_index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->field_index(), target);
  }

  // optional float val_f = 3;
  if (this->val_f() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->val_f(), target);
  }

  // optional int32 val_int = 4;
  if (this->val_int() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->val_int(), target);
  }

  // optional int64 val_bigint = 5;
  if (this->val_bigint() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->val_bigint(), target);
  }

  // optional string val_str = 6;
  if (this->val_str().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->val_str().data(), this->val_str().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protos.pb_table_field.val_str");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->val_str(), target);
  }

  // optional bool val_bool = 7;
  if (this->val_bool() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->val_bool(), target);
  }

  // optional bool primary = 8;
  if (this->primary() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->primary(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:protos.pb_table_field)
  return target;
}

int pb_table_field::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:protos.pb_table_field)
  int total_size = 0;

  // optional int32 val_type = 1;
  if (this->val_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->val_type());
  }

  // optional int32 field_index = 2;
  if (this->field_index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->field_index());
  }

  // optional float val_f = 3;
  if (this->val_f() != 0) {
    total_size += 1 + 4;
  }

  // optional int32 val_int = 4;
  if (this->val_int() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->val_int());
  }

  // optional int64 val_bigint = 5;
  if (this->val_bigint() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->val_bigint());
  }

  // optional string val_str = 6;
  if (this->val_str().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->val_str());
  }

  // optional bool val_bool = 7;
  if (this->val_bool() != 0) {
    total_size += 1 + 1;
  }

  // optional bool primary = 8;
  if (this->primary() != 0) {
    total_size += 1 + 1;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void pb_table_field::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protos.pb_table_field)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const pb_table_field* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const pb_table_field>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protos.pb_table_field)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protos.pb_table_field)
    MergeFrom(*source);
  }
}

void pb_table_field::MergeFrom(const pb_table_field& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protos.pb_table_field)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.val_type() != 0) {
    set_val_type(from.val_type());
  }
  if (from.field_index() != 0) {
    set_field_index(from.field_index());
  }
  if (from.val_f() != 0) {
    set_val_f(from.val_f());
  }
  if (from.val_int() != 0) {
    set_val_int(from.val_int());
  }
  if (from.val_bigint() != 0) {
    set_val_bigint(from.val_bigint());
  }
  if (from.val_str().size() > 0) {

    val_str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.val_str_);
  }
  if (from.val_bool() != 0) {
    set_val_bool(from.val_bool());
  }
  if (from.primary() != 0) {
    set_primary(from.primary());
  }
}

void pb_table_field::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protos.pb_table_field)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void pb_table_field::CopyFrom(const pb_table_field& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protos.pb_table_field)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pb_table_field::IsInitialized() const {

  return true;
}

void pb_table_field::Swap(pb_table_field* other) {
  if (other == this) return;
  InternalSwap(other);
}
void pb_table_field::InternalSwap(pb_table_field* other) {
  std::swap(val_type_, other->val_type_);
  std::swap(field_index_, other->field_index_);
  std::swap(val_f_, other->val_f_);
  std::swap(val_int_, other->val_int_);
  std::swap(val_bigint_, other->val_bigint_);
  val_str_.Swap(&other->val_str_);
  std::swap(val_bool_, other->val_bool_);
  std::swap(primary_, other->primary_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata pb_table_field::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = pb_table_field_descriptor_;
  metadata.reflection = pb_table_field_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// pb_table_field

// optional int32 val_type = 1;
void pb_table_field::clear_val_type() {
  val_type_ = 0;
}
 ::google::protobuf::int32 pb_table_field::val_type() const {
  // @@protoc_insertion_point(field_get:protos.pb_table_field.val_type)
  return val_type_;
}
 void pb_table_field::set_val_type(::google::protobuf::int32 value) {
  
  val_type_ = value;
  // @@protoc_insertion_point(field_set:protos.pb_table_field.val_type)
}

// optional int32 field_index = 2;
void pb_table_field::clear_field_index() {
  field_index_ = 0;
}
 ::google::protobuf::int32 pb_table_field::field_index() const {
  // @@protoc_insertion_point(field_get:protos.pb_table_field.field_index)
  return field_index_;
}
 void pb_table_field::set_field_index(::google::protobuf::int32 value) {
  
  field_index_ = value;
  // @@protoc_insertion_point(field_set:protos.pb_table_field.field_index)
}

// optional float val_f = 3;
void pb_table_field::clear_val_f() {
  val_f_ = 0;
}
 float pb_table_field::val_f() const {
  // @@protoc_insertion_point(field_get:protos.pb_table_field.val_f)
  return val_f_;
}
 void pb_table_field::set_val_f(float value) {
  
  val_f_ = value;
  // @@protoc_insertion_point(field_set:protos.pb_table_field.val_f)
}

// optional int32 val_int = 4;
void pb_table_field::clear_val_int() {
  val_int_ = 0;
}
 ::google::protobuf::int32 pb_table_field::val_int() const {
  // @@protoc_insertion_point(field_get:protos.pb_table_field.val_int)
  return val_int_;
}
 void pb_table_field::set_val_int(::google::protobuf::int32 value) {
  
  val_int_ = value;
  // @@protoc_insertion_point(field_set:protos.pb_table_field.val_int)
}

// optional int64 val_bigint = 5;
void pb_table_field::clear_val_bigint() {
  val_bigint_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 pb_table_field::val_bigint() const {
  // @@protoc_insertion_point(field_get:protos.pb_table_field.val_bigint)
  return val_bigint_;
}
 void pb_table_field::set_val_bigint(::google::protobuf::int64 value) {
  
  val_bigint_ = value;
  // @@protoc_insertion_point(field_set:protos.pb_table_field.val_bigint)
}

// optional string val_str = 6;
void pb_table_field::clear_val_str() {
  val_str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& pb_table_field::val_str() const {
  // @@protoc_insertion_point(field_get:protos.pb_table_field.val_str)
  return val_str_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void pb_table_field::set_val_str(const ::std::string& value) {
  
  val_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.pb_table_field.val_str)
}
 void pb_table_field::set_val_str(const char* value) {
  
  val_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.pb_table_field.val_str)
}
 void pb_table_field::set_val_str(const char* value, size_t size) {
  
  val_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.pb_table_field.val_str)
}
 ::std::string* pb_table_field::mutable_val_str() {
  
  // @@protoc_insertion_point(field_mutable:protos.pb_table_field.val_str)
  return val_str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* pb_table_field::release_val_str() {
  // @@protoc_insertion_point(field_release:protos.pb_table_field.val_str)
  
  return val_str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void pb_table_field::set_allocated_val_str(::std::string* val_str) {
  if (val_str != NULL) {
    
  } else {
    
  }
  val_str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), val_str);
  // @@protoc_insertion_point(field_set_allocated:protos.pb_table_field.val_str)
}

// optional bool val_bool = 7;
void pb_table_field::clear_val_bool() {
  val_bool_ = false;
}
 bool pb_table_field::val_bool() const {
  // @@protoc_insertion_point(field_get:protos.pb_table_field.val_bool)
  return val_bool_;
}
 void pb_table_field::set_val_bool(bool value) {
  
  val_bool_ = value;
  // @@protoc_insertion_point(field_set:protos.pb_table_field.val_bool)
}

// optional bool primary = 8;
void pb_table_field::clear_primary() {
  primary_ = false;
}
 bool pb_table_field::primary() const {
  // @@protoc_insertion_point(field_get:protos.pb_table_field.primary)
  return primary_;
}
 void pb_table_field::set_primary(bool value) {
  
  primary_ = value;
  // @@protoc_insertion_point(field_set:protos.pb_table_field.primary)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int pb_table_item::kFieldListFieldNumber;
const int pb_table_item::kDbStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

pb_table_item::pb_table_item()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protos.pb_table_item)
}

void pb_table_item::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

pb_table_item::pb_table_item(const pb_table_item& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protos.pb_table_item)
}

void pb_table_item::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  db_status_ = 0;
}

pb_table_item::~pb_table_item() {
  // @@protoc_insertion_point(destructor:protos.pb_table_item)
  SharedDtor();
}

void pb_table_item::SharedDtor() {
  if (this != default_instance_) {
  }
}

void pb_table_item::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* pb_table_item::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return pb_table_item_descriptor_;
}

const pb_table_item& pb_table_item::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_data_5fpb_5fcommon_2eproto();
  return *default_instance_;
}

pb_table_item* pb_table_item::default_instance_ = NULL;

pb_table_item* pb_table_item::New(::google::protobuf::Arena* arena) const {
  pb_table_item* n = new pb_table_item;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void pb_table_item::Clear() {
// @@protoc_insertion_point(message_clear_start:protos.pb_table_item)
  db_status_ = 0;
  field_list_.Clear();
}

bool pb_table_item::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protos.pb_table_item)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .protos.pb_table_field field_list = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_field_list:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_field_list()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_field_list;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(16)) goto parse_db_status;
        break;
      }

      // optional int32 db_status = 2;
      case 2: {
        if (tag == 16) {
         parse_db_status:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &db_status_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protos.pb_table_item)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protos.pb_table_item)
  return false;
#undef DO_
}

void pb_table_item::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protos.pb_table_item)
  // repeated .protos.pb_table_field field_list = 1;
  for (unsigned int i = 0, n = this->field_list_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->field_list(i), output);
  }

  // optional int32 db_status = 2;
  if (this->db_status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->db_status(), output);
  }

  // @@protoc_insertion_point(serialize_end:protos.pb_table_item)
}

::google::protobuf::uint8* pb_table_item::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protos.pb_table_item)
  // repeated .protos.pb_table_field field_list = 1;
  for (unsigned int i = 0, n = this->field_list_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->field_list(i), false, target);
  }

  // optional int32 db_status = 2;
  if (this->db_status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->db_status(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:protos.pb_table_item)
  return target;
}

int pb_table_item::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:protos.pb_table_item)
  int total_size = 0;

  // optional int32 db_status = 2;
  if (this->db_status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->db_status());
  }

  // repeated .protos.pb_table_field field_list = 1;
  total_size += 1 * this->field_list_size();
  for (int i = 0; i < this->field_list_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->field_list(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void pb_table_item::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protos.pb_table_item)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const pb_table_item* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const pb_table_item>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protos.pb_table_item)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protos.pb_table_item)
    MergeFrom(*source);
  }
}

void pb_table_item::MergeFrom(const pb_table_item& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protos.pb_table_item)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  field_list_.MergeFrom(from.field_list_);
  if (from.db_status() != 0) {
    set_db_status(from.db_status());
  }
}

void pb_table_item::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protos.pb_table_item)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void pb_table_item::CopyFrom(const pb_table_item& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protos.pb_table_item)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pb_table_item::IsInitialized() const {

  return true;
}

void pb_table_item::Swap(pb_table_item* other) {
  if (other == this) return;
  InternalSwap(other);
}
void pb_table_item::InternalSwap(pb_table_item* other) {
  field_list_.UnsafeArenaSwap(&other->field_list_);
  std::swap(db_status_, other->db_status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata pb_table_item::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = pb_table_item_descriptor_;
  metadata.reflection = pb_table_item_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// pb_table_item

// repeated .protos.pb_table_field field_list = 1;
int pb_table_item::field_list_size() const {
  return field_list_.size();
}
void pb_table_item::clear_field_list() {
  field_list_.Clear();
}
const ::protos::pb_table_field& pb_table_item::field_list(int index) const {
  // @@protoc_insertion_point(field_get:protos.pb_table_item.field_list)
  return field_list_.Get(index);
}
::protos::pb_table_field* pb_table_item::mutable_field_list(int index) {
  // @@protoc_insertion_point(field_mutable:protos.pb_table_item.field_list)
  return field_list_.Mutable(index);
}
::protos::pb_table_field* pb_table_item::add_field_list() {
  // @@protoc_insertion_point(field_add:protos.pb_table_item.field_list)
  return field_list_.Add();
}
::google::protobuf::RepeatedPtrField< ::protos::pb_table_field >*
pb_table_item::mutable_field_list() {
  // @@protoc_insertion_point(field_mutable_list:protos.pb_table_item.field_list)
  return &field_list_;
}
const ::google::protobuf::RepeatedPtrField< ::protos::pb_table_field >&
pb_table_item::field_list() const {
  // @@protoc_insertion_point(field_list:protos.pb_table_item.field_list)
  return field_list_;
}

// optional int32 db_status = 2;
void pb_table_item::clear_db_status() {
  db_status_ = 0;
}
 ::google::protobuf::int32 pb_table_item::db_status() const {
  // @@protoc_insertion_point(field_get:protos.pb_table_item.db_status)
  return db_status_;
}
 void pb_table_item::set_db_status(::google::protobuf::int32 value) {
  
  db_status_ = value;
  // @@protoc_insertion_point(field_set:protos.pb_table_item.db_status)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int pb_data_module::kTableIdFieldNumber;
const int pb_data_module::kDataItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

pb_data_module::pb_data_module()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protos.pb_data_module)
}

void pb_data_module::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

pb_data_module::pb_data_module(const pb_data_module& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protos.pb_data_module)
}

void pb_data_module::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  table_id_ = 0;
}

pb_data_module::~pb_data_module() {
  // @@protoc_insertion_point(destructor:protos.pb_data_module)
  SharedDtor();
}

void pb_data_module::SharedDtor() {
  if (this != default_instance_) {
  }
}

void pb_data_module::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* pb_data_module::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return pb_data_module_descriptor_;
}

const pb_data_module& pb_data_module::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_data_5fpb_5fcommon_2eproto();
  return *default_instance_;
}

pb_data_module* pb_data_module::default_instance_ = NULL;

pb_data_module* pb_data_module::New(::google::protobuf::Arena* arena) const {
  pb_data_module* n = new pb_data_module;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void pb_data_module::Clear() {
// @@protoc_insertion_point(message_clear_start:protos.pb_data_module)
  table_id_ = 0;
  data_items_.Clear();
}

bool pb_data_module::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protos.pb_data_module)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 table_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &table_id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_data_items;
        break;
      }

      // repeated .protos.pb_table_item data_items = 2;
      case 2: {
        if (tag == 18) {
         parse_data_items:
          DO_(input->IncrementRecursionDepth());
         parse_loop_data_items:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_data_items()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_data_items;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protos.pb_data_module)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protos.pb_data_module)
  return false;
#undef DO_
}

void pb_data_module::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protos.pb_data_module)
  // optional int32 table_id = 1;
  if (this->table_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->table_id(), output);
  }

  // repeated .protos.pb_table_item data_items = 2;
  for (unsigned int i = 0, n = this->data_items_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->data_items(i), output);
  }

  // @@protoc_insertion_point(serialize_end:protos.pb_data_module)
}

::google::protobuf::uint8* pb_data_module::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protos.pb_data_module)
  // optional int32 table_id = 1;
  if (this->table_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->table_id(), target);
  }

  // repeated .protos.pb_table_item data_items = 2;
  for (unsigned int i = 0, n = this->data_items_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->data_items(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:protos.pb_data_module)
  return target;
}

int pb_data_module::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:protos.pb_data_module)
  int total_size = 0;

  // optional int32 table_id = 1;
  if (this->table_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->table_id());
  }

  // repeated .protos.pb_table_item data_items = 2;
  total_size += 1 * this->data_items_size();
  for (int i = 0; i < this->data_items_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->data_items(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void pb_data_module::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protos.pb_data_module)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const pb_data_module* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const pb_data_module>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protos.pb_data_module)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protos.pb_data_module)
    MergeFrom(*source);
  }
}

void pb_data_module::MergeFrom(const pb_data_module& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protos.pb_data_module)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  data_items_.MergeFrom(from.data_items_);
  if (from.table_id() != 0) {
    set_table_id(from.table_id());
  }
}

void pb_data_module::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protos.pb_data_module)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void pb_data_module::CopyFrom(const pb_data_module& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protos.pb_data_module)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pb_data_module::IsInitialized() const {

  return true;
}

void pb_data_module::Swap(pb_data_module* other) {
  if (other == this) return;
  InternalSwap(other);
}
void pb_data_module::InternalSwap(pb_data_module* other) {
  std::swap(table_id_, other->table_id_);
  data_items_.UnsafeArenaSwap(&other->data_items_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata pb_data_module::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = pb_data_module_descriptor_;
  metadata.reflection = pb_data_module_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// pb_data_module

// optional int32 table_id = 1;
void pb_data_module::clear_table_id() {
  table_id_ = 0;
}
 ::google::protobuf::int32 pb_data_module::table_id() const {
  // @@protoc_insertion_point(field_get:protos.pb_data_module.table_id)
  return table_id_;
}
 void pb_data_module::set_table_id(::google::protobuf::int32 value) {
  
  table_id_ = value;
  // @@protoc_insertion_point(field_set:protos.pb_data_module.table_id)
}

// repeated .protos.pb_table_item data_items = 2;
int pb_data_module::data_items_size() const {
  return data_items_.size();
}
void pb_data_module::clear_data_items() {
  data_items_.Clear();
}
const ::protos::pb_table_item& pb_data_module::data_items(int index) const {
  // @@protoc_insertion_point(field_get:protos.pb_data_module.data_items)
  return data_items_.Get(index);
}
::protos::pb_table_item* pb_data_module::mutable_data_items(int index) {
  // @@protoc_insertion_point(field_mutable:protos.pb_data_module.data_items)
  return data_items_.Mutable(index);
}
::protos::pb_table_item* pb_data_module::add_data_items() {
  // @@protoc_insertion_point(field_add:protos.pb_data_module.data_items)
  return data_items_.Add();
}
::google::protobuf::RepeatedPtrField< ::protos::pb_table_item >*
pb_data_module::mutable_data_items() {
  // @@protoc_insertion_point(field_mutable_list:protos.pb_data_module.data_items)
  return &data_items_;
}
const ::google::protobuf::RepeatedPtrField< ::protos::pb_table_item >&
pb_data_module::data_items() const {
  // @@protoc_insertion_point(field_list:protos.pb_data_module.data_items)
  return data_items_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protos

// @@protoc_insertion_point(global_scope)
