// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protcl_login.proto

#ifndef PROTOBUF_protcl_5flogin_2eproto__INCLUDED
#define PROTOBUF_protcl_5flogin_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protos {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_protcl_5flogin_2eproto();
void protobuf_AssignDesc_protcl_5flogin_2eproto();
void protobuf_ShutdownFile_protcl_5flogin_2eproto();

class rep_E_LOGIN_MSG_C2S_LOGIN;
class rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT;
class rep_E_LOGIN_MSG_GG2ROOT_LOGIN;
class rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK;
class req_E_LOGIN_MSG_C2S_LOGIN;
class req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT;
class req_E_LOGIN_MSG_GG2ROOT_LOGIN;
class req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK;
class role_snapshot_t;

// ===================================================================

class req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT) */ {
 public:
  req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT();
  virtual ~req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT();

  req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT(const req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT& from);

  inline req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT& operator=(const req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT& default_instance();

  void Swap(req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT* other);

  // implements Message ----------------------------------------------

  inline req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT* New() const { return New(NULL); }

  req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT& from);
  void MergeFrom(const req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string account_name = 1;
  void clear_account_name();
  static const int kAccountNameFieldNumber = 1;
  const ::std::string& account_name() const;
  void set_account_name(const ::std::string& value);
  void set_account_name(const char* value);
  void set_account_name(const char* value, size_t size);
  ::std::string* mutable_account_name();
  ::std::string* release_account_name();
  void set_allocated_account_name(::std::string* account_name);

  // optional string pswd = 2;
  void clear_pswd();
  static const int kPswdFieldNumber = 2;
  const ::std::string& pswd() const;
  void set_pswd(const ::std::string& value);
  void set_pswd(const char* value);
  void set_pswd(const char* value, size_t size);
  ::std::string* mutable_pswd();
  ::std::string* release_pswd();
  void set_allocated_pswd(::std::string* pswd);

  // @@protoc_insertion_point(class_scope:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr account_name_;
  ::google::protobuf::internal::ArenaStringPtr pswd_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_protcl_5flogin_2eproto();
  friend void protobuf_AssignDesc_protcl_5flogin_2eproto();
  friend void protobuf_ShutdownFile_protcl_5flogin_2eproto();

  void InitAsDefaultInstance();
  static req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT* default_instance_;
};
// -------------------------------------------------------------------

class rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT) */ {
 public:
  rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT();
  virtual ~rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT();

  rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT(const rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT& from);

  inline rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT& operator=(const rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT& default_instance();

  void Swap(rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT* other);

  // implements Message ----------------------------------------------

  inline rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT* New() const { return New(NULL); }

  rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT& from);
  void MergeFrom(const rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 isok = 1;
  void clear_isok();
  static const int kIsokFieldNumber = 1;
  ::google::protobuf::int32 isok() const;
  void set_isok(::google::protobuf::int32 value);

  // optional string account_name = 2;
  void clear_account_name();
  static const int kAccountNameFieldNumber = 2;
  const ::std::string& account_name() const;
  void set_account_name(const ::std::string& value);
  void set_account_name(const char* value);
  void set_account_name(const char* value, size_t size);
  ::std::string* mutable_account_name();
  ::std::string* release_account_name();
  void set_allocated_account_name(::std::string* account_name);

  // optional string pswd = 3;
  void clear_pswd();
  static const int kPswdFieldNumber = 3;
  const ::std::string& pswd() const;
  void set_pswd(const ::std::string& value);
  void set_pswd(const char* value);
  void set_pswd(const char* value, size_t size);
  ::std::string* mutable_pswd();
  ::std::string* release_pswd();
  void set_allocated_pswd(::std::string* pswd);

  // optional int64 account_id = 4;
  void clear_account_id();
  static const int kAccountIdFieldNumber = 4;
  ::google::protobuf::int64 account_id() const;
  void set_account_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr account_name_;
  ::google::protobuf::internal::ArenaStringPtr pswd_;
  ::google::protobuf::int64 account_id_;
  ::google::protobuf::int32 isok_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_protcl_5flogin_2eproto();
  friend void protobuf_AssignDesc_protcl_5flogin_2eproto();
  friend void protobuf_ShutdownFile_protcl_5flogin_2eproto();

  void InitAsDefaultInstance();
  static rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT* default_instance_;
};
// -------------------------------------------------------------------

class role_snapshot_t : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.role_snapshot_t) */ {
 public:
  role_snapshot_t();
  virtual ~role_snapshot_t();

  role_snapshot_t(const role_snapshot_t& from);

  inline role_snapshot_t& operator=(const role_snapshot_t& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const role_snapshot_t& default_instance();

  void Swap(role_snapshot_t* other);

  // implements Message ----------------------------------------------

  inline role_snapshot_t* New() const { return New(NULL); }

  role_snapshot_t* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const role_snapshot_t& from);
  void MergeFrom(const role_snapshot_t& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(role_snapshot_t* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 role_id = 1;
  void clear_role_id();
  static const int kRoleIdFieldNumber = 1;
  ::google::protobuf::int64 role_id() const;
  void set_role_id(::google::protobuf::int64 value);

  // optional string nickname = 2;
  void clear_nickname();
  static const int kNicknameFieldNumber = 2;
  const ::std::string& nickname() const;
  void set_nickname(const ::std::string& value);
  void set_nickname(const char* value);
  void set_nickname(const char* value, size_t size);
  ::std::string* mutable_nickname();
  ::std::string* release_nickname();
  void set_allocated_nickname(::std::string* nickname);

  // @@protoc_insertion_point(class_scope:protos.role_snapshot_t)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 role_id_;
  ::google::protobuf::internal::ArenaStringPtr nickname_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_protcl_5flogin_2eproto();
  friend void protobuf_AssignDesc_protcl_5flogin_2eproto();
  friend void protobuf_ShutdownFile_protcl_5flogin_2eproto();

  void InitAsDefaultInstance();
  static role_snapshot_t* default_instance_;
};
// -------------------------------------------------------------------

class req_E_LOGIN_MSG_C2S_LOGIN : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.req_E_LOGIN_MSG_C2S_LOGIN) */ {
 public:
  req_E_LOGIN_MSG_C2S_LOGIN();
  virtual ~req_E_LOGIN_MSG_C2S_LOGIN();

  req_E_LOGIN_MSG_C2S_LOGIN(const req_E_LOGIN_MSG_C2S_LOGIN& from);

  inline req_E_LOGIN_MSG_C2S_LOGIN& operator=(const req_E_LOGIN_MSG_C2S_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const req_E_LOGIN_MSG_C2S_LOGIN& default_instance();

  void Swap(req_E_LOGIN_MSG_C2S_LOGIN* other);

  // implements Message ----------------------------------------------

  inline req_E_LOGIN_MSG_C2S_LOGIN* New() const { return New(NULL); }

  req_E_LOGIN_MSG_C2S_LOGIN* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const req_E_LOGIN_MSG_C2S_LOGIN& from);
  void MergeFrom(const req_E_LOGIN_MSG_C2S_LOGIN& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(req_E_LOGIN_MSG_C2S_LOGIN* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string account_name = 1;
  void clear_account_name();
  static const int kAccountNameFieldNumber = 1;
  const ::std::string& account_name() const;
  void set_account_name(const ::std::string& value);
  void set_account_name(const char* value);
  void set_account_name(const char* value, size_t size);
  ::std::string* mutable_account_name();
  ::std::string* release_account_name();
  void set_allocated_account_name(::std::string* account_name);

  // optional string pswd = 2;
  void clear_pswd();
  static const int kPswdFieldNumber = 2;
  const ::std::string& pswd() const;
  void set_pswd(const ::std::string& value);
  void set_pswd(const char* value);
  void set_pswd(const char* value, size_t size);
  ::std::string* mutable_pswd();
  ::std::string* release_pswd();
  void set_allocated_pswd(::std::string* pswd);

  // optional int64 account_id = 3;
  void clear_account_id();
  static const int kAccountIdFieldNumber = 3;
  ::google::protobuf::int64 account_id() const;
  void set_account_id(::google::protobuf::int64 value);

  // optional int32 zone_id = 4;
  void clear_zone_id();
  static const int kZoneIdFieldNumber = 4;
  ::google::protobuf::int32 zone_id() const;
  void set_zone_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.req_E_LOGIN_MSG_C2S_LOGIN)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr account_name_;
  ::google::protobuf::internal::ArenaStringPtr pswd_;
  ::google::protobuf::int64 account_id_;
  ::google::protobuf::int32 zone_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_protcl_5flogin_2eproto();
  friend void protobuf_AssignDesc_protcl_5flogin_2eproto();
  friend void protobuf_ShutdownFile_protcl_5flogin_2eproto();

  void InitAsDefaultInstance();
  static req_E_LOGIN_MSG_C2S_LOGIN* default_instance_;
};
// -------------------------------------------------------------------

class rep_E_LOGIN_MSG_C2S_LOGIN : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.rep_E_LOGIN_MSG_C2S_LOGIN) */ {
 public:
  rep_E_LOGIN_MSG_C2S_LOGIN();
  virtual ~rep_E_LOGIN_MSG_C2S_LOGIN();

  rep_E_LOGIN_MSG_C2S_LOGIN(const rep_E_LOGIN_MSG_C2S_LOGIN& from);

  inline rep_E_LOGIN_MSG_C2S_LOGIN& operator=(const rep_E_LOGIN_MSG_C2S_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const rep_E_LOGIN_MSG_C2S_LOGIN& default_instance();

  void Swap(rep_E_LOGIN_MSG_C2S_LOGIN* other);

  // implements Message ----------------------------------------------

  inline rep_E_LOGIN_MSG_C2S_LOGIN* New() const { return New(NULL); }

  rep_E_LOGIN_MSG_C2S_LOGIN* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const rep_E_LOGIN_MSG_C2S_LOGIN& from);
  void MergeFrom(const rep_E_LOGIN_MSG_C2S_LOGIN& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(rep_E_LOGIN_MSG_C2S_LOGIN* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 isok = 1;
  void clear_isok();
  static const int kIsokFieldNumber = 1;
  ::google::protobuf::int32 isok() const;
  void set_isok(::google::protobuf::int32 value);

  // repeated .protos.role_snapshot_t role_list = 2;
  int role_list_size() const;
  void clear_role_list();
  static const int kRoleListFieldNumber = 2;
  const ::protos::role_snapshot_t& role_list(int index) const;
  ::protos::role_snapshot_t* mutable_role_list(int index);
  ::protos::role_snapshot_t* add_role_list();
  ::google::protobuf::RepeatedPtrField< ::protos::role_snapshot_t >*
      mutable_role_list();
  const ::google::protobuf::RepeatedPtrField< ::protos::role_snapshot_t >&
      role_list() const;

  // @@protoc_insertion_point(class_scope:protos.rep_E_LOGIN_MSG_C2S_LOGIN)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::protos::role_snapshot_t > role_list_;
  ::google::protobuf::int32 isok_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_protcl_5flogin_2eproto();
  friend void protobuf_AssignDesc_protcl_5flogin_2eproto();
  friend void protobuf_ShutdownFile_protcl_5flogin_2eproto();

  void InitAsDefaultInstance();
  static rep_E_LOGIN_MSG_C2S_LOGIN* default_instance_;
};
// -------------------------------------------------------------------

class req_E_LOGIN_MSG_GG2ROOT_LOGIN : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN) */ {
 public:
  req_E_LOGIN_MSG_GG2ROOT_LOGIN();
  virtual ~req_E_LOGIN_MSG_GG2ROOT_LOGIN();

  req_E_LOGIN_MSG_GG2ROOT_LOGIN(const req_E_LOGIN_MSG_GG2ROOT_LOGIN& from);

  inline req_E_LOGIN_MSG_GG2ROOT_LOGIN& operator=(const req_E_LOGIN_MSG_GG2ROOT_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const req_E_LOGIN_MSG_GG2ROOT_LOGIN& default_instance();

  void Swap(req_E_LOGIN_MSG_GG2ROOT_LOGIN* other);

  // implements Message ----------------------------------------------

  inline req_E_LOGIN_MSG_GG2ROOT_LOGIN* New() const { return New(NULL); }

  req_E_LOGIN_MSG_GG2ROOT_LOGIN* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const req_E_LOGIN_MSG_GG2ROOT_LOGIN& from);
  void MergeFrom(const req_E_LOGIN_MSG_GG2ROOT_LOGIN& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(req_E_LOGIN_MSG_GG2ROOT_LOGIN* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string account_name = 1;
  void clear_account_name();
  static const int kAccountNameFieldNumber = 1;
  const ::std::string& account_name() const;
  void set_account_name(const ::std::string& value);
  void set_account_name(const char* value);
  void set_account_name(const char* value, size_t size);
  ::std::string* mutable_account_name();
  ::std::string* release_account_name();
  void set_allocated_account_name(::std::string* account_name);

  // optional string pswd = 2;
  void clear_pswd();
  static const int kPswdFieldNumber = 2;
  const ::std::string& pswd() const;
  void set_pswd(const ::std::string& value);
  void set_pswd(const char* value);
  void set_pswd(const char* value, size_t size);
  ::std::string* mutable_pswd();
  ::std::string* release_pswd();
  void set_allocated_pswd(::std::string* pswd);

  // optional int64 account_id = 3;
  void clear_account_id();
  static const int kAccountIdFieldNumber = 3;
  ::google::protobuf::int64 account_id() const;
  void set_account_id(::google::protobuf::int64 value);

  // optional int32 zone_id = 4;
  void clear_zone_id();
  static const int kZoneIdFieldNumber = 4;
  ::google::protobuf::int32 zone_id() const;
  void set_zone_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr account_name_;
  ::google::protobuf::internal::ArenaStringPtr pswd_;
  ::google::protobuf::int64 account_id_;
  ::google::protobuf::int32 zone_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_protcl_5flogin_2eproto();
  friend void protobuf_AssignDesc_protcl_5flogin_2eproto();
  friend void protobuf_ShutdownFile_protcl_5flogin_2eproto();

  void InitAsDefaultInstance();
  static req_E_LOGIN_MSG_GG2ROOT_LOGIN* default_instance_;
};
// -------------------------------------------------------------------

class rep_E_LOGIN_MSG_GG2ROOT_LOGIN : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.rep_E_LOGIN_MSG_GG2ROOT_LOGIN) */ {
 public:
  rep_E_LOGIN_MSG_GG2ROOT_LOGIN();
  virtual ~rep_E_LOGIN_MSG_GG2ROOT_LOGIN();

  rep_E_LOGIN_MSG_GG2ROOT_LOGIN(const rep_E_LOGIN_MSG_GG2ROOT_LOGIN& from);

  inline rep_E_LOGIN_MSG_GG2ROOT_LOGIN& operator=(const rep_E_LOGIN_MSG_GG2ROOT_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const rep_E_LOGIN_MSG_GG2ROOT_LOGIN& default_instance();

  void Swap(rep_E_LOGIN_MSG_GG2ROOT_LOGIN* other);

  // implements Message ----------------------------------------------

  inline rep_E_LOGIN_MSG_GG2ROOT_LOGIN* New() const { return New(NULL); }

  rep_E_LOGIN_MSG_GG2ROOT_LOGIN* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const rep_E_LOGIN_MSG_GG2ROOT_LOGIN& from);
  void MergeFrom(const rep_E_LOGIN_MSG_GG2ROOT_LOGIN& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(rep_E_LOGIN_MSG_GG2ROOT_LOGIN* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 isok = 1;
  void clear_isok();
  static const int kIsokFieldNumber = 1;
  ::google::protobuf::int32 isok() const;
  void set_isok(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.rep_E_LOGIN_MSG_GG2ROOT_LOGIN)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 isok_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_protcl_5flogin_2eproto();
  friend void protobuf_AssignDesc_protcl_5flogin_2eproto();
  friend void protobuf_ShutdownFile_protcl_5flogin_2eproto();

  void InitAsDefaultInstance();
  static rep_E_LOGIN_MSG_GG2ROOT_LOGIN* default_instance_;
};
// -------------------------------------------------------------------

class req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK) */ {
 public:
  req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK();
  virtual ~req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK();

  req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK(const req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK& from);

  inline req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK& operator=(const req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK& default_instance();

  void Swap(req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK* other);

  // implements Message ----------------------------------------------

  inline req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK* New() const { return New(NULL); }

  req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK& from);
  void MergeFrom(const req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string account_name = 1;
  void clear_account_name();
  static const int kAccountNameFieldNumber = 1;
  const ::std::string& account_name() const;
  void set_account_name(const ::std::string& value);
  void set_account_name(const char* value);
  void set_account_name(const char* value, size_t size);
  ::std::string* mutable_account_name();
  ::std::string* release_account_name();
  void set_allocated_account_name(::std::string* account_name);

  // optional string pswd = 2;
  void clear_pswd();
  static const int kPswdFieldNumber = 2;
  const ::std::string& pswd() const;
  void set_pswd(const ::std::string& value);
  void set_pswd(const char* value);
  void set_pswd(const char* value, size_t size);
  ::std::string* mutable_pswd();
  ::std::string* release_pswd();
  void set_allocated_pswd(::std::string* pswd);

  // optional int64 account_id = 3;
  void clear_account_id();
  static const int kAccountIdFieldNumber = 3;
  ::google::protobuf::int64 account_id() const;
  void set_account_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr account_name_;
  ::google::protobuf::internal::ArenaStringPtr pswd_;
  ::google::protobuf::int64 account_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_protcl_5flogin_2eproto();
  friend void protobuf_AssignDesc_protcl_5flogin_2eproto();
  friend void protobuf_ShutdownFile_protcl_5flogin_2eproto();

  void InitAsDefaultInstance();
  static req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK* default_instance_;
};
// -------------------------------------------------------------------

class rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK) */ {
 public:
  rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK();
  virtual ~rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK();

  rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK(const rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK& from);

  inline rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK& operator=(const rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK& default_instance();

  void Swap(rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK* other);

  // implements Message ----------------------------------------------

  inline rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK* New() const { return New(NULL); }

  rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK& from);
  void MergeFrom(const rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 isok = 1;
  void clear_isok();
  static const int kIsokFieldNumber = 1;
  ::google::protobuf::int32 isok() const;
  void set_isok(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protos.rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 isok_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_protcl_5flogin_2eproto();
  friend void protobuf_AssignDesc_protcl_5flogin_2eproto();
  friend void protobuf_ShutdownFile_protcl_5flogin_2eproto();

  void InitAsDefaultInstance();
  static rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT

// optional string account_name = 1;
inline void req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::clear_account_name() {
  account_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::account_name() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
  return account_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_account_name(const ::std::string& value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
}
inline void req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_account_name(const char* value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
}
inline void req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_account_name(const char* value, size_t size) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
}
inline ::std::string* req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::mutable_account_name() {
  
  // @@protoc_insertion_point(field_mutable:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
  return account_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::release_account_name() {
  // @@protoc_insertion_point(field_release:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
  
  return account_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_allocated_account_name(::std::string* account_name) {
  if (account_name != NULL) {
    
  } else {
    
  }
  account_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account_name);
  // @@protoc_insertion_point(field_set_allocated:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
}

// optional string pswd = 2;
inline void req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::clear_pswd() {
  pswd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::pswd() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
  return pswd_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_pswd(const ::std::string& value) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
}
inline void req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_pswd(const char* value) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
}
inline void req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_pswd(const char* value, size_t size) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
}
inline ::std::string* req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::mutable_pswd() {
  
  // @@protoc_insertion_point(field_mutable:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
  return pswd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::release_pswd() {
  // @@protoc_insertion_point(field_release:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
  
  return pswd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_allocated_pswd(::std::string* pswd) {
  if (pswd != NULL) {
    
  } else {
    
  }
  pswd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pswd);
  // @@protoc_insertion_point(field_set_allocated:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
}

// -------------------------------------------------------------------

// rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT

// optional int32 isok = 1;
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::clear_isok() {
  isok_ = 0;
}
inline ::google::protobuf::int32 rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::isok() const {
  // @@protoc_insertion_point(field_get:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.isok)
  return isok_;
}
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_isok(::google::protobuf::int32 value) {
  
  isok_ = value;
  // @@protoc_insertion_point(field_set:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.isok)
}

// optional string account_name = 2;
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::clear_account_name() {
  account_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::account_name() const {
  // @@protoc_insertion_point(field_get:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
  return account_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_account_name(const ::std::string& value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
}
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_account_name(const char* value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
}
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_account_name(const char* value, size_t size) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
}
inline ::std::string* rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::mutable_account_name() {
  
  // @@protoc_insertion_point(field_mutable:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
  return account_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::release_account_name() {
  // @@protoc_insertion_point(field_release:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
  
  return account_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_allocated_account_name(::std::string* account_name) {
  if (account_name != NULL) {
    
  } else {
    
  }
  account_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account_name);
  // @@protoc_insertion_point(field_set_allocated:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name)
}

// optional string pswd = 3;
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::clear_pswd() {
  pswd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::pswd() const {
  // @@protoc_insertion_point(field_get:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
  return pswd_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_pswd(const ::std::string& value) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
}
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_pswd(const char* value) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
}
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_pswd(const char* value, size_t size) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
}
inline ::std::string* rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::mutable_pswd() {
  
  // @@protoc_insertion_point(field_mutable:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
  return pswd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::release_pswd() {
  // @@protoc_insertion_point(field_release:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
  
  return pswd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_allocated_pswd(::std::string* pswd) {
  if (pswd != NULL) {
    
  } else {
    
  }
  pswd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pswd);
  // @@protoc_insertion_point(field_set_allocated:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd)
}

// optional int64 account_id = 4;
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::clear_account_id() {
  account_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::account_id() const {
  // @@protoc_insertion_point(field_get:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_id)
  return account_id_;
}
inline void rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT::set_account_id(::google::protobuf::int64 value) {
  
  account_id_ = value;
  // @@protoc_insertion_point(field_set:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_id)
}

// -------------------------------------------------------------------

// role_snapshot_t

// optional int64 role_id = 1;
inline void role_snapshot_t::clear_role_id() {
  role_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 role_snapshot_t::role_id() const {
  // @@protoc_insertion_point(field_get:protos.role_snapshot_t.role_id)
  return role_id_;
}
inline void role_snapshot_t::set_role_id(::google::protobuf::int64 value) {
  
  role_id_ = value;
  // @@protoc_insertion_point(field_set:protos.role_snapshot_t.role_id)
}

// optional string nickname = 2;
inline void role_snapshot_t::clear_nickname() {
  nickname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& role_snapshot_t::nickname() const {
  // @@protoc_insertion_point(field_get:protos.role_snapshot_t.nickname)
  return nickname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void role_snapshot_t::set_nickname(const ::std::string& value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.role_snapshot_t.nickname)
}
inline void role_snapshot_t::set_nickname(const char* value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.role_snapshot_t.nickname)
}
inline void role_snapshot_t::set_nickname(const char* value, size_t size) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.role_snapshot_t.nickname)
}
inline ::std::string* role_snapshot_t::mutable_nickname() {
  
  // @@protoc_insertion_point(field_mutable:protos.role_snapshot_t.nickname)
  return nickname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* role_snapshot_t::release_nickname() {
  // @@protoc_insertion_point(field_release:protos.role_snapshot_t.nickname)
  
  return nickname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void role_snapshot_t::set_allocated_nickname(::std::string* nickname) {
  if (nickname != NULL) {
    
  } else {
    
  }
  nickname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nickname);
  // @@protoc_insertion_point(field_set_allocated:protos.role_snapshot_t.nickname)
}

// -------------------------------------------------------------------

// req_E_LOGIN_MSG_C2S_LOGIN

// optional string account_name = 1;
inline void req_E_LOGIN_MSG_C2S_LOGIN::clear_account_name() {
  account_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& req_E_LOGIN_MSG_C2S_LOGIN::account_name() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_C2S_LOGIN.account_name)
  return account_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_C2S_LOGIN::set_account_name(const ::std::string& value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_C2S_LOGIN.account_name)
}
inline void req_E_LOGIN_MSG_C2S_LOGIN::set_account_name(const char* value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.req_E_LOGIN_MSG_C2S_LOGIN.account_name)
}
inline void req_E_LOGIN_MSG_C2S_LOGIN::set_account_name(const char* value, size_t size) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.req_E_LOGIN_MSG_C2S_LOGIN.account_name)
}
inline ::std::string* req_E_LOGIN_MSG_C2S_LOGIN::mutable_account_name() {
  
  // @@protoc_insertion_point(field_mutable:protos.req_E_LOGIN_MSG_C2S_LOGIN.account_name)
  return account_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* req_E_LOGIN_MSG_C2S_LOGIN::release_account_name() {
  // @@protoc_insertion_point(field_release:protos.req_E_LOGIN_MSG_C2S_LOGIN.account_name)
  
  return account_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_C2S_LOGIN::set_allocated_account_name(::std::string* account_name) {
  if (account_name != NULL) {
    
  } else {
    
  }
  account_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account_name);
  // @@protoc_insertion_point(field_set_allocated:protos.req_E_LOGIN_MSG_C2S_LOGIN.account_name)
}

// optional string pswd = 2;
inline void req_E_LOGIN_MSG_C2S_LOGIN::clear_pswd() {
  pswd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& req_E_LOGIN_MSG_C2S_LOGIN::pswd() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_C2S_LOGIN.pswd)
  return pswd_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_C2S_LOGIN::set_pswd(const ::std::string& value) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_C2S_LOGIN.pswd)
}
inline void req_E_LOGIN_MSG_C2S_LOGIN::set_pswd(const char* value) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.req_E_LOGIN_MSG_C2S_LOGIN.pswd)
}
inline void req_E_LOGIN_MSG_C2S_LOGIN::set_pswd(const char* value, size_t size) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.req_E_LOGIN_MSG_C2S_LOGIN.pswd)
}
inline ::std::string* req_E_LOGIN_MSG_C2S_LOGIN::mutable_pswd() {
  
  // @@protoc_insertion_point(field_mutable:protos.req_E_LOGIN_MSG_C2S_LOGIN.pswd)
  return pswd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* req_E_LOGIN_MSG_C2S_LOGIN::release_pswd() {
  // @@protoc_insertion_point(field_release:protos.req_E_LOGIN_MSG_C2S_LOGIN.pswd)
  
  return pswd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_C2S_LOGIN::set_allocated_pswd(::std::string* pswd) {
  if (pswd != NULL) {
    
  } else {
    
  }
  pswd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pswd);
  // @@protoc_insertion_point(field_set_allocated:protos.req_E_LOGIN_MSG_C2S_LOGIN.pswd)
}

// optional int64 account_id = 3;
inline void req_E_LOGIN_MSG_C2S_LOGIN::clear_account_id() {
  account_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 req_E_LOGIN_MSG_C2S_LOGIN::account_id() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_C2S_LOGIN.account_id)
  return account_id_;
}
inline void req_E_LOGIN_MSG_C2S_LOGIN::set_account_id(::google::protobuf::int64 value) {
  
  account_id_ = value;
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_C2S_LOGIN.account_id)
}

// optional int32 zone_id = 4;
inline void req_E_LOGIN_MSG_C2S_LOGIN::clear_zone_id() {
  zone_id_ = 0;
}
inline ::google::protobuf::int32 req_E_LOGIN_MSG_C2S_LOGIN::zone_id() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_C2S_LOGIN.zone_id)
  return zone_id_;
}
inline void req_E_LOGIN_MSG_C2S_LOGIN::set_zone_id(::google::protobuf::int32 value) {
  
  zone_id_ = value;
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_C2S_LOGIN.zone_id)
}

// -------------------------------------------------------------------

// rep_E_LOGIN_MSG_C2S_LOGIN

// optional int32 isok = 1;
inline void rep_E_LOGIN_MSG_C2S_LOGIN::clear_isok() {
  isok_ = 0;
}
inline ::google::protobuf::int32 rep_E_LOGIN_MSG_C2S_LOGIN::isok() const {
  // @@protoc_insertion_point(field_get:protos.rep_E_LOGIN_MSG_C2S_LOGIN.isok)
  return isok_;
}
inline void rep_E_LOGIN_MSG_C2S_LOGIN::set_isok(::google::protobuf::int32 value) {
  
  isok_ = value;
  // @@protoc_insertion_point(field_set:protos.rep_E_LOGIN_MSG_C2S_LOGIN.isok)
}

// repeated .protos.role_snapshot_t role_list = 2;
inline int rep_E_LOGIN_MSG_C2S_LOGIN::role_list_size() const {
  return role_list_.size();
}
inline void rep_E_LOGIN_MSG_C2S_LOGIN::clear_role_list() {
  role_list_.Clear();
}
inline const ::protos::role_snapshot_t& rep_E_LOGIN_MSG_C2S_LOGIN::role_list(int index) const {
  // @@protoc_insertion_point(field_get:protos.rep_E_LOGIN_MSG_C2S_LOGIN.role_list)
  return role_list_.Get(index);
}
inline ::protos::role_snapshot_t* rep_E_LOGIN_MSG_C2S_LOGIN::mutable_role_list(int index) {
  // @@protoc_insertion_point(field_mutable:protos.rep_E_LOGIN_MSG_C2S_LOGIN.role_list)
  return role_list_.Mutable(index);
}
inline ::protos::role_snapshot_t* rep_E_LOGIN_MSG_C2S_LOGIN::add_role_list() {
  // @@protoc_insertion_point(field_add:protos.rep_E_LOGIN_MSG_C2S_LOGIN.role_list)
  return role_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::protos::role_snapshot_t >*
rep_E_LOGIN_MSG_C2S_LOGIN::mutable_role_list() {
  // @@protoc_insertion_point(field_mutable_list:protos.rep_E_LOGIN_MSG_C2S_LOGIN.role_list)
  return &role_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::protos::role_snapshot_t >&
rep_E_LOGIN_MSG_C2S_LOGIN::role_list() const {
  // @@protoc_insertion_point(field_list:protos.rep_E_LOGIN_MSG_C2S_LOGIN.role_list)
  return role_list_;
}

// -------------------------------------------------------------------

// req_E_LOGIN_MSG_GG2ROOT_LOGIN

// optional string account_name = 1;
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::clear_account_name() {
  account_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& req_E_LOGIN_MSG_GG2ROOT_LOGIN::account_name() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.account_name)
  return account_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::set_account_name(const ::std::string& value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.account_name)
}
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::set_account_name(const char* value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.account_name)
}
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::set_account_name(const char* value, size_t size) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.account_name)
}
inline ::std::string* req_E_LOGIN_MSG_GG2ROOT_LOGIN::mutable_account_name() {
  
  // @@protoc_insertion_point(field_mutable:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.account_name)
  return account_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* req_E_LOGIN_MSG_GG2ROOT_LOGIN::release_account_name() {
  // @@protoc_insertion_point(field_release:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.account_name)
  
  return account_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::set_allocated_account_name(::std::string* account_name) {
  if (account_name != NULL) {
    
  } else {
    
  }
  account_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account_name);
  // @@protoc_insertion_point(field_set_allocated:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.account_name)
}

// optional string pswd = 2;
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::clear_pswd() {
  pswd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& req_E_LOGIN_MSG_GG2ROOT_LOGIN::pswd() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.pswd)
  return pswd_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::set_pswd(const ::std::string& value) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.pswd)
}
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::set_pswd(const char* value) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.pswd)
}
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::set_pswd(const char* value, size_t size) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.pswd)
}
inline ::std::string* req_E_LOGIN_MSG_GG2ROOT_LOGIN::mutable_pswd() {
  
  // @@protoc_insertion_point(field_mutable:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.pswd)
  return pswd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* req_E_LOGIN_MSG_GG2ROOT_LOGIN::release_pswd() {
  // @@protoc_insertion_point(field_release:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.pswd)
  
  return pswd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::set_allocated_pswd(::std::string* pswd) {
  if (pswd != NULL) {
    
  } else {
    
  }
  pswd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pswd);
  // @@protoc_insertion_point(field_set_allocated:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.pswd)
}

// optional int64 account_id = 3;
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::clear_account_id() {
  account_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 req_E_LOGIN_MSG_GG2ROOT_LOGIN::account_id() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.account_id)
  return account_id_;
}
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::set_account_id(::google::protobuf::int64 value) {
  
  account_id_ = value;
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.account_id)
}

// optional int32 zone_id = 4;
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::clear_zone_id() {
  zone_id_ = 0;
}
inline ::google::protobuf::int32 req_E_LOGIN_MSG_GG2ROOT_LOGIN::zone_id() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.zone_id)
  return zone_id_;
}
inline void req_E_LOGIN_MSG_GG2ROOT_LOGIN::set_zone_id(::google::protobuf::int32 value) {
  
  zone_id_ = value;
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.zone_id)
}

// -------------------------------------------------------------------

// rep_E_LOGIN_MSG_GG2ROOT_LOGIN

// optional int32 isok = 1;
inline void rep_E_LOGIN_MSG_GG2ROOT_LOGIN::clear_isok() {
  isok_ = 0;
}
inline ::google::protobuf::int32 rep_E_LOGIN_MSG_GG2ROOT_LOGIN::isok() const {
  // @@protoc_insertion_point(field_get:protos.rep_E_LOGIN_MSG_GG2ROOT_LOGIN.isok)
  return isok_;
}
inline void rep_E_LOGIN_MSG_GG2ROOT_LOGIN::set_isok(::google::protobuf::int32 value) {
  
  isok_ = value;
  // @@protoc_insertion_point(field_set:protos.rep_E_LOGIN_MSG_GG2ROOT_LOGIN.isok)
}

// -------------------------------------------------------------------

// req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK

// optional string account_name = 1;
inline void req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::clear_account_name() {
  account_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::account_name() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.account_name)
  return account_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::set_account_name(const ::std::string& value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.account_name)
}
inline void req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::set_account_name(const char* value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.account_name)
}
inline void req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::set_account_name(const char* value, size_t size) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.account_name)
}
inline ::std::string* req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::mutable_account_name() {
  
  // @@protoc_insertion_point(field_mutable:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.account_name)
  return account_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::release_account_name() {
  // @@protoc_insertion_point(field_release:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.account_name)
  
  return account_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::set_allocated_account_name(::std::string* account_name) {
  if (account_name != NULL) {
    
  } else {
    
  }
  account_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account_name);
  // @@protoc_insertion_point(field_set_allocated:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.account_name)
}

// optional string pswd = 2;
inline void req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::clear_pswd() {
  pswd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::pswd() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.pswd)
  return pswd_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::set_pswd(const ::std::string& value) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.pswd)
}
inline void req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::set_pswd(const char* value) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.pswd)
}
inline void req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::set_pswd(const char* value, size_t size) {
  
  pswd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.pswd)
}
inline ::std::string* req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::mutable_pswd() {
  
  // @@protoc_insertion_point(field_mutable:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.pswd)
  return pswd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::release_pswd() {
  // @@protoc_insertion_point(field_release:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.pswd)
  
  return pswd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::set_allocated_pswd(::std::string* pswd) {
  if (pswd != NULL) {
    
  } else {
    
  }
  pswd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pswd);
  // @@protoc_insertion_point(field_set_allocated:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.pswd)
}

// optional int64 account_id = 3;
inline void req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::clear_account_id() {
  account_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::account_id() const {
  // @@protoc_insertion_point(field_get:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.account_id)
  return account_id_;
}
inline void req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::set_account_id(::google::protobuf::int64 value) {
  
  account_id_ = value;
  // @@protoc_insertion_point(field_set:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.account_id)
}

// -------------------------------------------------------------------

// rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK

// optional int32 isok = 1;
inline void rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::clear_isok() {
  isok_ = 0;
}
inline ::google::protobuf::int32 rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::isok() const {
  // @@protoc_insertion_point(field_get:protos.rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.isok)
  return isok_;
}
inline void rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK::set_isok(::google::protobuf::int32 value) {
  
  isok_ = value;
  // @@protoc_insertion_point(field_set:protos.rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.isok)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protos

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protcl_5flogin_2eproto__INCLUDED
