# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protcl_login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protcl_login.proto',
  package='protos',
  syntax='proto3',
  serialized_pb=_b('\n\x12protcl_login.proto\x12\x06protos\"J\n$req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\t\x12\x0c\n\x04pswd\x18\x02 \x01(\t\"l\n$rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT\x12\x0c\n\x04isok\x18\x01 \x01(\x05\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x02 \x01(\t\x12\x0c\n\x04pswd\x18\x03 \x01(\t\x12\x12\n\naccount_id\x18\x04 \x01(\x03\"4\n\x0frole_snapshot_t\x12\x0f\n\x07role_id\x18\x01 \x01(\x03\x12\x10\n\x08nickname\x18\x02 \x01(\t\"d\n\x19req_E_LOGIN_MSG_C2S_LOGIN\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\t\x12\x0c\n\x04pswd\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\x03\x12\x0f\n\x07zone_id\x18\x04 \x01(\x05\"U\n\x19rep_E_LOGIN_MSG_C2S_LOGIN\x12\x0c\n\x04isok\x18\x01 \x01(\x05\x12*\n\trole_list\x18\x02 \x03(\x0b\x32\x17.protos.role_snapshot_t\"h\n\x1dreq_E_LOGIN_MSG_GG2ROOT_LOGIN\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\t\x12\x0c\n\x04pswd\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\x03\x12\x0f\n\x07zone_id\x18\x04 \x01(\x05\"-\n\x1drep_E_LOGIN_MSG_GG2ROOT_LOGIN\x12\x0c\n\x04isok\x18\x01 \x01(\x05\"_\n%req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\t\x12\x0c\n\x04pswd\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\x03\"5\n%rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK\x12\x0c\n\x04isok\x18\x01 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQ_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT = _descriptor.Descriptor(
  name='req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT',
  full_name='protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_name', full_name='protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pswd', full_name='protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=104,
)


_REP_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT = _descriptor.Descriptor(
  name='rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT',
  full_name='protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isok', full_name='protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.isok', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_name', full_name='protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pswd', full_name='protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.pswd', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT.account_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=214,
)


_ROLE_SNAPSHOT_T = _descriptor.Descriptor(
  name='role_snapshot_t',
  full_name='protos.role_snapshot_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='protos.role_snapshot_t.role_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='protos.role_snapshot_t.nickname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=268,
)


_REQ_E_LOGIN_MSG_C2S_LOGIN = _descriptor.Descriptor(
  name='req_E_LOGIN_MSG_C2S_LOGIN',
  full_name='protos.req_E_LOGIN_MSG_C2S_LOGIN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_name', full_name='protos.req_E_LOGIN_MSG_C2S_LOGIN.account_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pswd', full_name='protos.req_E_LOGIN_MSG_C2S_LOGIN.pswd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='protos.req_E_LOGIN_MSG_C2S_LOGIN.account_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zone_id', full_name='protos.req_E_LOGIN_MSG_C2S_LOGIN.zone_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=370,
)


_REP_E_LOGIN_MSG_C2S_LOGIN = _descriptor.Descriptor(
  name='rep_E_LOGIN_MSG_C2S_LOGIN',
  full_name='protos.rep_E_LOGIN_MSG_C2S_LOGIN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isok', full_name='protos.rep_E_LOGIN_MSG_C2S_LOGIN.isok', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role_list', full_name='protos.rep_E_LOGIN_MSG_C2S_LOGIN.role_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=457,
)


_REQ_E_LOGIN_MSG_GG2ROOT_LOGIN = _descriptor.Descriptor(
  name='req_E_LOGIN_MSG_GG2ROOT_LOGIN',
  full_name='protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_name', full_name='protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.account_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pswd', full_name='protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.pswd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.account_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zone_id', full_name='protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN.zone_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=563,
)


_REP_E_LOGIN_MSG_GG2ROOT_LOGIN = _descriptor.Descriptor(
  name='rep_E_LOGIN_MSG_GG2ROOT_LOGIN',
  full_name='protos.rep_E_LOGIN_MSG_GG2ROOT_LOGIN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isok', full_name='protos.rep_E_LOGIN_MSG_GG2ROOT_LOGIN.isok', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=610,
)


_REQ_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK = _descriptor.Descriptor(
  name='req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK',
  full_name='protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_name', full_name='protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.account_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pswd', full_name='protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.pswd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.account_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=612,
  serialized_end=707,
)


_REP_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK = _descriptor.Descriptor(
  name='rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK',
  full_name='protos.rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isok', full_name='protos.rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK.isok', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=709,
  serialized_end=762,
)

_REP_E_LOGIN_MSG_C2S_LOGIN.fields_by_name['role_list'].message_type = _ROLE_SNAPSHOT_T
DESCRIPTOR.message_types_by_name['req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT'] = _REQ_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT
DESCRIPTOR.message_types_by_name['rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT'] = _REP_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT
DESCRIPTOR.message_types_by_name['role_snapshot_t'] = _ROLE_SNAPSHOT_T
DESCRIPTOR.message_types_by_name['req_E_LOGIN_MSG_C2S_LOGIN'] = _REQ_E_LOGIN_MSG_C2S_LOGIN
DESCRIPTOR.message_types_by_name['rep_E_LOGIN_MSG_C2S_LOGIN'] = _REP_E_LOGIN_MSG_C2S_LOGIN
DESCRIPTOR.message_types_by_name['req_E_LOGIN_MSG_GG2ROOT_LOGIN'] = _REQ_E_LOGIN_MSG_GG2ROOT_LOGIN
DESCRIPTOR.message_types_by_name['rep_E_LOGIN_MSG_GG2ROOT_LOGIN'] = _REP_E_LOGIN_MSG_GG2ROOT_LOGIN
DESCRIPTOR.message_types_by_name['req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK'] = _REQ_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK
DESCRIPTOR.message_types_by_name['rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK'] = _REP_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK

req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT = _reflection.GeneratedProtocolMessageType('req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT', (_message.Message,), dict(
  DESCRIPTOR = _REQ_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT,
  __module__ = 'protcl_login_pb2'
  # @@protoc_insertion_point(class_scope:protos.req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT)
  ))
_sym_db.RegisterMessage(req_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT)

rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT = _reflection.GeneratedProtocolMessageType('rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT', (_message.Message,), dict(
  DESCRIPTOR = _REP_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT,
  __module__ = 'protcl_login_pb2'
  # @@protoc_insertion_point(class_scope:protos.rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT)
  ))
_sym_db.RegisterMessage(rep_E_LOGIN_MSG_C2S_REGISTER_ACCOUNT)

role_snapshot_t = _reflection.GeneratedProtocolMessageType('role_snapshot_t', (_message.Message,), dict(
  DESCRIPTOR = _ROLE_SNAPSHOT_T,
  __module__ = 'protcl_login_pb2'
  # @@protoc_insertion_point(class_scope:protos.role_snapshot_t)
  ))
_sym_db.RegisterMessage(role_snapshot_t)

req_E_LOGIN_MSG_C2S_LOGIN = _reflection.GeneratedProtocolMessageType('req_E_LOGIN_MSG_C2S_LOGIN', (_message.Message,), dict(
  DESCRIPTOR = _REQ_E_LOGIN_MSG_C2S_LOGIN,
  __module__ = 'protcl_login_pb2'
  # @@protoc_insertion_point(class_scope:protos.req_E_LOGIN_MSG_C2S_LOGIN)
  ))
_sym_db.RegisterMessage(req_E_LOGIN_MSG_C2S_LOGIN)

rep_E_LOGIN_MSG_C2S_LOGIN = _reflection.GeneratedProtocolMessageType('rep_E_LOGIN_MSG_C2S_LOGIN', (_message.Message,), dict(
  DESCRIPTOR = _REP_E_LOGIN_MSG_C2S_LOGIN,
  __module__ = 'protcl_login_pb2'
  # @@protoc_insertion_point(class_scope:protos.rep_E_LOGIN_MSG_C2S_LOGIN)
  ))
_sym_db.RegisterMessage(rep_E_LOGIN_MSG_C2S_LOGIN)

req_E_LOGIN_MSG_GG2ROOT_LOGIN = _reflection.GeneratedProtocolMessageType('req_E_LOGIN_MSG_GG2ROOT_LOGIN', (_message.Message,), dict(
  DESCRIPTOR = _REQ_E_LOGIN_MSG_GG2ROOT_LOGIN,
  __module__ = 'protcl_login_pb2'
  # @@protoc_insertion_point(class_scope:protos.req_E_LOGIN_MSG_GG2ROOT_LOGIN)
  ))
_sym_db.RegisterMessage(req_E_LOGIN_MSG_GG2ROOT_LOGIN)

rep_E_LOGIN_MSG_GG2ROOT_LOGIN = _reflection.GeneratedProtocolMessageType('rep_E_LOGIN_MSG_GG2ROOT_LOGIN', (_message.Message,), dict(
  DESCRIPTOR = _REP_E_LOGIN_MSG_GG2ROOT_LOGIN,
  __module__ = 'protcl_login_pb2'
  # @@protoc_insertion_point(class_scope:protos.rep_E_LOGIN_MSG_GG2ROOT_LOGIN)
  ))
_sym_db.RegisterMessage(rep_E_LOGIN_MSG_GG2ROOT_LOGIN)

req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK = _reflection.GeneratedProtocolMessageType('req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK', (_message.Message,), dict(
  DESCRIPTOR = _REQ_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK,
  __module__ = 'protcl_login_pb2'
  # @@protoc_insertion_point(class_scope:protos.req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK)
  ))
_sym_db.RegisterMessage(req_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK)

rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK = _reflection.GeneratedProtocolMessageType('rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK', (_message.Message,), dict(
  DESCRIPTOR = _REP_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK,
  __module__ = 'protcl_login_pb2'
  # @@protoc_insertion_point(class_scope:protos.rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK)
  ))
_sym_db.RegisterMessage(rep_E_LOGIN_MSG_ROOT2LOGIN_ACCT_CHECK)


# @@protoc_insertion_point(module_scope)
